---
-   hosts: localhost
    gather_facts: no

    tasks:

    - name: Check that you can connect (GET) to CUCM and if it returns a status 200
      uri:
        url: https://10.142.0.1:8443/emservice/EMServiceServlet
        validate_certs: no
        method: POST
        return_content: yes
        headers:
            Content-Type: "application/x-www-form-urlencoded"
        force_basic_auth: yes
        body: 'xml=%3crequest%3e%3cappInfo%3e%3cappID%3edevnet%3c%2fappID%3e%3cappCertificate%3edevnet%3c%2fappCertificate%3e%3c%2fappInfo%3e%3clogin%3e%3cdeviceName%3eSEP0013C352FFDA%3c%2fdeviceName%3e%3cuserID%3e{{username_mm}}%3c%2fuserID%3e%3c%2flogin%3e%3c%2frequest%3e'
      register: page_content

#    - debug:
#        var: page_content.content


    - name: Verifico su PRIME la sessione relativa al MAC address del telefono predefinito
      uri:
        url: 'https://10.23.77.200/webacs/api/v4/data/ClientSessions.json?macAddress=0013C352FFDA&.sort=-id&.maxResults=1'
        validate_certs: no
        method: GET
        return_content: yes
        body_format: json
        headers:
            Content-Type: "application/json"
        user: devnet
        password: Maticmind2018
        force_basic_auth: yes
      register: prime_sessions

#    - debug:
#        var: prime_sessions.content
      

    - name: prendo il risultato della sessione PRIME e lo piazzo su un Dictionary
      set_fact: 
         prime_json: "{{prime_sessions.content | from_json }}"

#    - debug:
#        msg: "{{prime_json}}"
    
    - name: Prendo l'URL relativo alla sessione
      set_fact:
        prime_session_url: "{{prime_json['queryResponse']['entityId'][0]['@url']}}"
     
#    - debug:
#            var: prime_session_url

    - name: GET the detailed info of the highest session ID in JSON format
      uri:
        url: '{{prime_session_url}}.json'
        validate_certs: no
        method: GET
        return_content: yes
        body_format: json
        headers:
            Content-Type: "application/json"
        user: devnet
        password: Maticmind2018
        force_basic_auth: yes
      register: session_facts

#    - debug:
#        var: session_facts.content
    
    - name: parse the JSON output from CPI and save it in a new dictionary
      set_fact: 
         prime_json_session: "{{session_facts.content | from_json }}"

      
    - name: GET the switch MGMT IP Address where the MAC is connected
      set_fact: 
         switch_IP: "{{prime_json_session.queryResponse.entity.0.clientSessionsDTO.deviceMgmtAddress.address}}"

    - debug:
        var: switch_IP
      
    - name: GET the switch interface number where the MAC is connected
      set_fact: 
         switch_Interface: "{{prime_json_session.queryResponse.entity.0.clientSessionsDTO.clientInterface}}"

    - debug:
        var: switch_Interface
      
    - name: GET the switch hostname
      set_fact: 
         switch_hostname: "{{prime_json_session.queryResponse.entity.0.clientSessionsDTO.deviceName}}"

#    - debug:
#        var: switch_hostname


-   hosts: MM_Vimodrone
    gather_facts: no
    connection: network_cli

    vars:
      ansible_network_os: ios

    tasks:

#    - debug:
#       var: hostvars['localhost']['switch_Interface']

    - ios_command:
        commands:
          - configure terminal
          - interface {{hostvars['localhost']['switch_Interface']}}
          - no power inline never
          - description telefono di {{username_mm}}
          - end
      when: ansible_host== hostvars['localhost']['switch_IP']
