---
- hosts: localhost
#  gather_facts: no
#  connection: httpapi

# vars:
#   ansible_network_os: ios

  tasks:

  - name: Check that you can connect (GET) to CUCM and it returns a status 200
    uri:
      url: https://10.142.0.1:8443/axl/
      validate_certs: no
      headers:
       Content-Type: "application/xml"
      user: devnet
      password: devnet
      body_format: xml
      force_basic_auth: yes
    
# Check that a page returns a status 200 and fail if the word AXL is not
# in the page contents.

#- name: Check if CUCM returns AXL in its content
#  uri:
#    url: https://10.142.0.1:8443/axl/
#    user: devnet
#    password: devnet
#    force_basic_auth: yes
#    return_content: yes
#  register: page_content
#  failed_when: "'AXL' not in page_content.content"

#- name: POST "something" on CUCM!
#  uri:
#    url: https://10.142.0.1:8443/axl/
#    method: POST
#    body_format: raw
#    user: devnet
#    password: devnet
#    body: 
#    "{{ 
#    "<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/10.5">
#     <soapenv:Header/>
#     <soapenv:Body>
#      <ns:executeSQLQuery>
#         <sql>
#            SELECT DISTINCT d.name AS device_name, tm.name AS device_type, eu.userid, eu.firstname, eu.lastname
#            FROM device d
#            LEFT OUTER JOIN enduser eu on d.fkenduser=eu.pkid
#            INNER JOIN typemodel tm on d.tkmodel=tm.enum
#            WHERE eu.userid LIKE 'aseghezzi' and d.name LIKE 'SEP%'
#            ORDER BY eu.userid
#        </sql>
#      </ns:executeSQLQuery>
#     </soapenv:Body>
#     </soapenv:Envelope>"
#
#     }}"
#    force_basic_auth: yes
#    status_code: 201
#    body_format: raw

# Login to a form based webpage, then use the returned cookie to
# access the app in later tasks
#
#- uri:
#    url: https://your.form.based.auth.example.com/index.php
#    method: POST
#    body_format: form-urlencoded
#    body:
#      name: your_username
#      password: your_password
#      enter: Sign in
#    status_code: 302
#  register: login
           
#<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/10.5">
#    <soapenv:Header/>
#    <soapenv:Body>
#        <ns:getPhone>
#            <name>SEP000C29E85240</name>
#        </ns:getPhone>
#    </soapenv:Body>
#</soapenv:Envelope>
