---
-   hosts: localhost
    gather_facts: no
#  connection: httpapi

# vars:
#   ansible_network_os: ios

    tasks:

    - name: Check that you can connect (GET) to CUCM and if it returns a status 200
      uri:
        url: https://10.142.0.1:8443/axl/
        validate_certs: no
        method: POST
        return_content: yes
        headers:
            Content-Type: "text/plain"
        user: devnet
        password: devnet
        force_basic_auth: yes
        body: <soapenv:Envelope xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' xmlns:ns='http://www.cisco.com/AXL/API/10.5'><soapenv:Header/><soapenv:Body><ns:executeSQLQuery><sql>SELECT DISTINCT d.name AS device_name,tm.name AS device_type,eu.userid,eu.firstname,eu.lastname FROM device d LEFT OUTER JOIN enduser eu on d.fkenduser=eu.pkid INNER JOIN typemodel tm on d.tkmodel=tm.enum WHERE eu.userid LIKE 'aseghezzi' and d.name LIKE 'SEP%' ORDER BY eu.userid</sql></ns:executeSQLQuery></soapenv:Body></soapenv:Envelope>
      register: page_content

    - xml:
        xmlstring: "{{page_content.content}}"
        xpath: /soapenv:Envelope/soapenv:Body/ns:executeSQLQueryResponse/return/row/device_name
        namespaces:
            soapenv: http://schemas.xmlsoap.org/soap/envelope/
            ns: http://www.cisco.com/AXL/API/10.5
        content: text
      register: phone_mac
      
    - name: get_mac_address
      set_fact: 
         mac_device: "{{phone_mac.matches.0.device_name}}"

    - debug:
        var: mac_device
 
    - name: get_clean_mac_address
      set_fact: 
         clean_mac: "{{ mac_device | regex_replace('SEP') }}"

    - debug:
        var: clean_mac

    - name: get_mac_session_from_PRIME
      uri:
        url: https://10.23.77.200/webacs/api/v4/data/ClientSessions
        validate_certs: no¨
        method: GET
        body: "macAddress=\"{{clean_mac}}\""
        return_content: yes
        headers:
            Content-Type: "application/x-www-form-urlencoded"
        user: devnet
        password: Maticmind2018
        force_basic_auth: yes
      register: prime_session

    - debug:
        var: prime_session
      
