---
-   hosts: localhost
    gather_facts: yes

    tasks:

    - name: GET the cpu values from CPI
      uri:
        url: 'https://10.23.77.200/webacs/api/v4/op/statisticsService/device/topNCPU.json?range=1&topN=50'
        validate_certs: no
        method: GET
        return_content: yes
        body_format: json
        headers:
            Content-Type: "application/json"
        user: devnet
        password: Maticmind2018
        force_basic_auth: yes
      register: prime_topn_cpu

#    - debug:
#        var: prime_topn_cpu.content
      

    - name: parse the JSON output from CPI and save it in a new dictionary
      set_fact: 
         prime_topn_cpu_json: "{{prime_topn_cpu.content | from_json }}"

#    - debug:
#        msg: "{{prime_topn_cpu_json}}"
    
    - name: set db fields to stored 
      uri:
        url: 'http://10.23.77.202:9200/cpu-{{ansible_date_time.date}}'
        method: PUT
        return_content: yes
        body_format: json
        body: '{
                "mappings": {
                    "switch": {
                        "properties": {
                                "deviceName" : {
                                    "type": "text",
                                    "store" : true    
                                },
                                "deviceIp" : {
                                    "type": "text",
                                    "store" : true
                                },
                                "avgUtil" : {
                                    "type": "long",
                                    "store" : true
                                },
                                "maxUtil" : {
                                    "type": "long",
                                    "store" : true
                                },
                                "minUtil" : {
                                    "type": "long",
                                    "store" : true
                                },
                                "curUtil" : {
                                    "type": "long",
                                    "store" : true
                                },
                                "Datetime" : {
                                    "type": "date",
                                    "store" : true
                                },
                                "Myindex" : {
                                    "type": "long",
                                    "store" : true
                                }
                        }
                    }
                }
               }'
        headers:
            Content-Type: "application/json"
        status_code: [201, 200, 400]
         
    - name: save output to elastic
      uri:
        url: 'http://10.23.77.202:9200/cpu-{{ansible_date_time.date}}/switch/'
        method: POST
        return_content: yes
        body_format: json
        body: '{
                "{{item.statisticEntries.statisticEntry.0.attributeName}}":"{{item.statisticEntries.statisticEntry.0.entryValue}}",
                "{{item.statisticEntries.statisticEntry.1.attributeName}}":"{{item.statisticEntries.statisticEntry.1.entryValue}}",
                "{{item.statisticEntries.statisticEntry.2.attributeName}}":"{{item.statisticEntries.statisticEntry.2.entryValue}}",
                "{{item.statisticEntries.statisticEntry.3.attributeName}}":"{{item.statisticEntries.statisticEntry.3.entryValue}}",
                "{{item.statisticEntries.statisticEntry.4.attributeName}}":"{{item.statisticEntries.statisticEntry.4.entryValue}}",
                "{{item.statisticEntries.statisticEntry.5.attributeName}}":"{{item.statisticEntries.statisticEntry.5.entryValue}}",
                "{{item.statisticEntries.statisticEntry.6.attributeName}}":"{{item.statisticEntries.statisticEntry.6.entryValue}}",
                "@timestamp":"{{ansible_date_time.iso8601}}",
                "Datetime":"{{ansible_date_time.iso8601}}",
                "Myindex":"{{ 1000000 | random }}"
                }'
        headers:
            Content-Type: "application/json"
        status_code: 201
      register: elastic_result
      with_items: "{{prime_topn_cpu_json.mgmtResponse.statisticsDTO}}"

    - debug:
        msg: "{{ansible_date_time.iso8601}}"

