---
- hosts: MM_Vimodrone_DEVNET
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: ios
    username_mm: 'fmenezes'
  
  tasks:

  - name: run multiple commands on switch DEVNET
    ios_command:
      commands:
        - configure terminal
        - interface {{switch_Int}}
        - no power inline never
        - description chissa
        - end
        - wr
      
#    when: username_mm == "fmenezes"
   
  - debug:
      msg: "The received username is {{ username_mm }} so PWR is granted"
    when: username_mm == "fmenezes"

  - debug:
      msg: "The received username is {{ username_mm }} so PWR is NOT granted"
    when: username_mm != "fmenezes"

    

      
    
