---
- hosts: MM_Vimodrone_DEVNET
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: ios
#    username_mm: 'fmenezes'
  
  tasks:

  - name: run multiple commands on switch DEVNET
    ios_command:
      commands:
        - configure terminal
        - interface GigabitEthernet1/0/2
        - no power inline never
        - end
        - wr
      
    when: username_mm == "fmenezes"
   
  - debug:
      msg: "The received username is {{ username_mm }}"
    when: username_mm == "fmenezes"

  - debug:
      msg: "The received username is {{ username_mm }}"
    when: username_mm != "fmenezes"

    

      
    
